# Generated by Django 5.1.6 on 2025-03-02 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Startpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('colour', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='CactiD',
        ),
        migrations.DeleteModel(
            name='Darkwoods',
        ),
        migrations.DeleteModel(
            name='Desert',
        ),
        migrations.DeleteModel(
            name='Jungle',
        ),
        migrations.DeleteModel(
            name='Oakwoods',
        ),
        migrations.DeleteModel(
            name='Tundra',
        ),
    ]
